// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triumph.Web.Data;

namespace Triumph.Web.Migrations
{
    [DbContext(typeof(TriumphDbContext))]
    [Migration("20181219144256_EmployeeMigration2")]
    partial class EmployeeMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("Triumph.Web.Entities.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Url");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssignedEmpID");

                    b.Property<string>("BusinessName");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Notes");

                    b.Property<string>("Phone");

                    b.HasKey("ClientID");

                    b.HasIndex("AssignedEmpID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Employees", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Notes");

                    b.Property<string>("Phone");

                    b.HasKey("EmpID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Todo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssignedClientIDClientID");

                    b.Property<int?>("AssignedEmpIDEmpID");

                    b.Property<string>("Attributes");

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("Name");

                    b.Property<string>("Priority");

                    b.HasKey("ID");

                    b.HasIndex("AssignedClientIDClientID");

                    b.HasIndex("AssignedEmpIDEmpID");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Client", b =>
                {
                    b.HasOne("Triumph.Web.Entities.Employees", "Assigned")
                        .WithMany()
                        .HasForeignKey("AssignedEmpID");
                });

            modelBuilder.Entity("Triumph.Web.Entities.Post", b =>
                {
                    b.HasOne("Triumph.Web.Entities.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Triumph.Web.Entities.Todo", b =>
                {
                    b.HasOne("Triumph.Web.Entities.Client", "AssignedClientID")
                        .WithMany()
                        .HasForeignKey("AssignedClientIDClientID");

                    b.HasOne("Triumph.Web.Entities.Employees", "AssignedEmpID")
                        .WithMany()
                        .HasForeignKey("AssignedEmpIDEmpID");
                });
#pragma warning restore 612, 618
        }
    }
}
